![image.png|500](https://picturerealm.oss-cn-chengdu.aliyuncs.com/obsidian/20250312155110516.png)

In [1]:
# 首先我们需要理解np.array的基本用法
import numpy as np

In [3]:
# 创建一维数组
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [5]:
# 创建矩阵
A = np.array(
    [[1,2,3],
    [4,5,6]]
)
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 检查看数组的维度
a.ndim,A.ndim,a.shape,A.shape,a.size,A.size,a.dtype,A.dtype
#* ndim: 数组的维度
#* shape: 数组的形状
#* size: 数组的元素个数
#* dtype: 数组的数据类型

(1, 2, (6,), (2, 3), 6, 6, dtype('int64'), dtype('int64'))

In [21]:
# 创建全部是1的数组
np.ones(8),np.ones(8,dtype = 'int64'),np.ones(8,dtype = 'float64'),np.ones(shape = (2,4))

(array([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1]),
 array([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [23]:
# 创建一个形状相同的数组
np.ones_like(a),np.ones_like(A)

(array([1, 1, 1, 1, 1, 1]),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [25]:
# 创建全部都是0的数组
np.zeros(8),np.zeros_like(a)

(array([0., 0., 0., 0., 0., 0., 0., 0.]), array([0, 0, 0, 0, 0, 0]))

In [28]:
# 指定数值
print(np.full(8,666)) #* 创建一个全部是666的数组，一维数组，8个元素
print(np.full(shape = (2,4), fill_value = 666)) #* 创建一个2行4列的矩阵，全部是666

[666 666 666 666 666 666 666 666]
[[666 666 666 666]
 [666 666 666 666]]


In [46]:
# 创建空数组
print(np.empty(8)) #! 为什么不是0？因为空数组的内容是未初始化的，可能包含任何值
print(np.empty((2,4)))


[3.29e-321 3.29e-321 3.29e-321 3.29e-321 3.29e-321 3.29e-321 3.29e-321
 3.29e-321]
[[3.29e-321 3.29e-321 3.29e-321 3.29e-321]
 [3.29e-321 3.29e-321 3.29e-321 3.29e-321]]


In [ ]:
#重点
#!创建等差数组
print(np.arange(1,10,2)) #* 从1开始，到10结束，步长为2
print(np.arange(10)) #* 从0开始，到9结束
print(np.arange(10).reshape(2,5)) #* 从0开始，到9结束，步长为2，重塑为2行5列的矩阵

[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [53]:
print(np.linspace(0,10,5)) #* 从0到10，生成5个等间距的数

[ 0.   2.5  5.   7.5 10. ]


In [61]:
#重点
#! 创建随机数
print(np.random.random()) #* 生成一个0到1之间的随机数
print(np.random.random(3)) #* 生成一个包含3个0到1之间的随机数的一维数组
print(np.random.random((2,3))) #* 生成一个2行3列的矩阵，包含0到1之间的随机数

0.5304897022166523
[0.2909821  0.8588775  0.67723855]
[[0.98930715 0.00856194 0.44526001]
 [0.68518372 0.4630881  0.81470143]]


In [64]:
#! rand和random的区别
#! rand和random的不同之处在于，rand是numpy的函数，random是python自带的函数。
print(np.random.rand()) #* 生成一个0到1之间的随机数
print(np.random.rand(2,3)) #* 生成一个2行3列的矩阵，包含0到1之间的随机数


0.7608506379724377
[[0.39256614 0.13966212 0.31644321]
 [0.01244878 0.54245457 0.19355982]]


In [90]:
# 创建随机整数
print(np.random.randint(5)) #* 生成一个0到5之间的随机整数
print(np.random.randint(5,10)) #* 生成一个5到10之间的随机整数
print(np.random.randint(5,10,size = (2,3))) #* 生成一个2行3列的矩阵，包含5到10之间的随机整数

1
9
[[6 8 8]
 [8 8 9]]


In [91]:
# 随机种子
np.random.seed(42) #* 设置随机种子，确保每次运行生成的随机数相同
print(np.random.randint(5,10,size = (2,3))) #* 生成一个2行3列的矩阵，包含5到10之间的随机整数

[[8 9 7]
 [9 9 6]]


In [113]:
# 正态分布随机数
print(np.random.normal()) #* 生成一个正态分布的随机数
print(np.random.normal(10,1000,20)) #* 生成一个均值为10，标准差为1000，大小为20的正态分布随机数
print(np.random.normal(10,1000,size = (4,6))) #* 生成一个均值为10，标准差为1000，形状为4行6列的正态分布随机数矩阵

1.392325753491903
[ -870.64081853    86.89494858  -483.4324822    933.16260834
  1716.60495368   883.58941564    19.14434574  -355.53929683
   659.08673263 -1212.87353668   546.33603238  -904.69093126
   630.54821596  -150.93737686  -378.26439898  -875.51237383
  -346.74502577   566.12179853  1053.86061092   536.44816133]
[[ 1373.88652442  2549.16271627  -314.49095783  -195.8667171
  -1430.04144768  1200.72725611]
 [ 1309.39681426  -857.14615605   627.64084551  1227.07079698
    236.2882695    857.40143258]
 [  184.83301199 -1206.85489236  1059.34739232  1335.10566151
    744.50106488  -944.49726196]
 [ -741.17942466 -1120.42805312   779.97735993  1278.3895224
    434.48624406   950.53558496]]


In [123]:
# 均匀分布
print(np.random.uniform())
print(np.random.uniform(1, 5)) #* 生成一个1到5之间的均匀分布随机数
print(np.random.uniform(1, 5,size=(2,3))) #* 生成一个2行3列的矩阵，包含1到5之间的均匀分布随机数

0.936154774160781
3.784119186699892
[[3.28024468 1.38870598 3.46002891]
 [4.9602154  1.56033606 3.07331861]]
