In [2]:
import numpy as np

# 本节学习内容
本节主要学习numpy索引的创建方法。

In [6]:
# 用小写字母代表一维数组，用大写字母代表矩阵
a = np.arange(10) #* 创建一个一维数组，包含0到9的整数
A = np.arange(20).reshape(4, 5) #* 创建一个4行5列的矩阵，包含0到19的整数
a,A

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [ ]:
print(a[0]) #* 访问一维数组的第一个元素
print(a[-1]) #* 访问一维数组的最后一个元素
print(a[0:5]) #* 访问一维数组的前5个元素
print(a[:]) #* 访问一维数组的所有元素


0
9
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [16]:
#!重点，每隔1个元素取一个
print(a[::2]) #* 访问一维数组的所有元素，步长为2
print(a[::-1])  #* 访问一维数组的所有元素，步长为-1（逆序）

[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [22]:
# 矩阵
print(A) #* 访问矩阵的第一行
print(A[0,0]) #* 访问矩阵的第1行第1列元素
print(A[0, :]) #* 访问矩阵的第1行所有列
print(A[:, 0]) #* 访问矩阵的所有行第1列
print(A[0:2, 0:3]) #* 访问矩阵的前2行前3列
print(A[::-1, ::-1]) #* 访问矩阵的所有元素，步长为-1（逆序）

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
[0 1 2 3 4]
[ 0  5 10 15]
[[0 1 2]
 [5 6 7]]
[[19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [31]:
#! 重点，numpy中赋值后，原数组会被修改
X = A[:2,:3] #* 访问矩阵的前2行前3列
#! 如果修改X，A也会被修改
X[0,0] = 666 #* 修改X的第1行第1
print(A) #* 查看A的变化


[[666   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [33]:
#! 如果不想修改原数组，可以使用copy方法
X = A[:2,:3].copy() #* 访问矩阵的前2行前3列，并复制一份
X[0,0] = 999 #* 修改X的第1行第1
print(A) #* 查看A的变化

[[666   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
