In [1]:
import numpy as np

# 本节介绍
本节课主要学习numpy数组的合并和拆分方法。

In [18]:
X = np.arange(12).reshape(4, 3)  #* 创建一个3行4列的矩阵
a = np.array([6,6,6]) #* 创建一个一维数组
print(X,a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] [6 6 6]


In [21]:
#! 重点，将2个数组合并
A = np.concatenate((X,a.reshape(1,3))) #* 默认情况下，沿着第0轴（行）合并
print(A) #* 查看合并后的结果
#! 但是concatenate函数比较复杂，我们可以使用更简单的函数来合并数组
print(np.vstack((X,a))) #* 沿着第0轴（行）合并
#! 合并时，要求合并的数组在其他轴上的维度必须相同
a2 = np.array([6,6,6,6]) #* 创建一个一维数组
print(np.hstack((X,a2.reshape(4,1)))) #* 沿着第1轴（列）合并

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 6  6  6]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 6  6  6]]
[[ 0  1  2  6]
 [ 3  4  5  6]
 [ 6  7  8  6]
 [ 9 10 11  6]]


接下来学习拆分操作

In [27]:
print(X) #* 查看X的内容


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
X1,X2 = np.split(X, [-1]) #* 沿着第0轴（行）拆分,从第-1行开始拆分
print(f"按照水平（默认）拆分：\n{X1}\n{X2}") #* 查看拆分后的结果
X1,X2 = np.split(X, [-1], axis=1) #* 沿着第1轴（列）拆分,从第-1列开始拆分
print(f"按照垂直拆分：\n{X1}\n{X2}") #* 查看拆分后的结果
#* 也可以使用hsplit和vsplit函数来拆分数组
X1,X2 = np.vsplit(X, [-1]) 
print(f"使用vsplit函数拆分：\n{X1}\n{X2}") #* 查看拆分后的结果
X1,X2 = np.hsplit(X, [-1]) 
print(f"使用hsplit函数拆分：\n{X1}\n{X2}") #* 查看拆分后的结果


按照水平（默认）拆分：
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]
按照垂直拆分：
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
使用vsplit函数拆分：
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]
使用hsplit函数拆分：
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]


In [44]:
#拆分呈多个数组
X1,X2,X3 = np.hsplit(X, [1,2])
print(f"拆分成多个数组：\n{X1}\n{X2}\n{X3}") #* 查看拆分后的结果

拆分成多个数组：
[[0]
 [3]
 [6]
 [9]]
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
